<div class="col-lg-12 col-sm-12 col-xs-12 jtv-main-home-slider">
        <div style="position:relative;width:100%;height:auto;margin-top:10px;margin-bottom:10px" class="forcefullwidth_wrapper_tp_banner"><div id="rev_slider_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="left: -104.5px; position: absolute; width: 1349px; overflow: visible; height: 500px;">
          <div id="rev_slider_1" class="rev_slider fullwidthabanner revslider-initialised tp-simpleresponsive hovered" style="max-height: 500px; background-color: rgba(0, 0, 0, 0); background-image: none; height: 500px;">
            <ul style="display: block; overflow: hidden; width: 100%; height: 100%; max-height: none;">
              <li data-transition="slotzoom-horizontal" data-slotamount="7" data-masterspeed="1000" data-thumb="images/slider/slide-img1.jpg" style="width: 100%; height: 100%; overflow: hidden; visibility: visible; left: 0px; top: 0px; z-index: 18; opacity: 1;"><div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="left top" data-kenburns="undefined" data-easeme="undefined" data-bgfit="cover" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined"><div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat" data-lazydone="undefined" src="images/slider/slide-img1.jpg" data-src="images/slider/slide-img1.jpg" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;images/slider/slide-img1.jpg&quot;); background-size: cover; background-position: left top; width: 100%; height: 100%; opacity: 0;"></div></div>
                <div class="info">
                  <div class="tp-caption ExtraLargeTitle sft tp-resizeme start" data-x="0" data-y="165" data-endspeed="500" data-speed="500" data-start="1100" data-easing="Linear.easeNone" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" style="z-index: 2; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 69px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 16px; left: 141px; top: 165px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, -50, 0, 1);"><span style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 30px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 36px;">Shop The Trend</span></div>
                  <div class="tp-caption LargeTitle sfl tp-resizeme start" data-x="0" data-y="220" data-endspeed="500" data-speed="500" data-start="1300" data-easing="Linear.easeNone" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" style="z-index: 3; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 70px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 1px; font-size: 49px; left: 141px; top: 220px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, -50, 0, 0, 1);">Amazing Chance!</div>
                  <div class="tp-caption Title sft tp-resizeme start" data-x="0" data-y="300" data-endspeed="500" data-speed="500" data-start="1500" data-easing="Power2.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 20px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 1px; font-size: 16px; left: 141px; top: 300px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, -50, 0, 1);">Our new arrivals can't wait to meet you.</div>
                  <div class="tp-caption sfb tp-resizeme start" data-x="0" data-y="350" data-endspeed="500" data-speed="500" data-start="1500" data-easing="Linear.easeNone" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 17px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 12px; left: 141px; top: 350px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, 50, 0, 1);"><a href="#" class="buy-btn" style="transition: all 0.4s ease 0s; min-height: 0px; min-width: 0px; line-height: 20px; border-width: 1px; margin: 0px 0px 0px 10px; padding: 12px 20px; letter-spacing: 2px; font-size: 14px;">Browse Now</a></div>
                </div>
              </li>
              <li data-transition="slotzoom-horizontal" data-slotamount="7" data-masterspeed="1000" data-thumb="images/slider/slide-img3.jpg" style="width: 100%; height: 100%; overflow: hidden; visibility: visible; left: 0px; top: 0px; z-index: 20; opacity: 1;"><div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="left top" data-kenburns="undefined" data-easeme="undefined" data-bgfit="cover" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined"><div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat" data-lazydone="undefined" src="images/slider/slide-img3.jpg" data-src="images/slider/slide-img3.jpg" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;images/slider/slide-img3.jpg&quot;); background-size: cover; background-position: left top; width: 100%; height: 100%; opacity: 1;"></div></div>
                <div class="info">
                  <div class="tp-caption ExtraLargeTitle sft slide2 tp-resizeme start" data-x="45" data-y="165" data-endspeed="500" data-speed="500" data-start="1100" data-easing="Linear.easeNone" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" style="z-index: 2; white-space: nowrap; padding: 0px; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 69px; border-width: 0px; margin: 0px; letter-spacing: 0px; font-size: 16px; left: 186px; top: 165px; visibility: visible; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.0025, 0, 0, 0, 1);"><span style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 30px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 36px;">Spring Fashion</span></div>
                  <div class="tp-caption LargeTitle sfl tp-resizeme start" data-x="45" data-y="220" data-endspeed="500" data-speed="500" data-start="1300" data-easing="Linear.easeNone" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" style="z-index: 3; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 70px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 1px; font-size: 49px; left: 186px; top: 220px; visibility: visible; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.0025, 0, 0, 0, 1);">Be Summer Ready</div>
                  <div class="tp-caption Title sft tp-resizeme start" data-x="45" data-y="300" data-endspeed="500" data-speed="500" data-start="1500" data-easing="Power2.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 20px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 1px; font-size: 16px; left: 186px; top: 300px; visibility: visible; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.0025, 0, 0, 0, 1);">Identify your Look, Define your Style!</div>
                  <div class="tp-caption sfb tp-resizeme start" data-x="45" data-y="350" data-endspeed="500" data-speed="500" data-start="1500" data-easing="Linear.easeNone" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 17px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 12px; left: 186px; top: 350px; visibility: visible; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.0025, 0, 0, 0, 1);"><a href="#" class="buy-btn" style="transition: all 0.4s ease 0s; min-height: 0px; min-width: 0px; line-height: 20px; border-width: 1px; margin: 0px 0px 0px 10px; padding: 12px 20px; letter-spacing: 2px; font-size: 14px;">Join us</a></div>
                </div>
              </li>
              <li data-transition="slotzoom-horizontal" data-slotamount="7" data-masterspeed="1000" data-thumb="images/slider/slide-img2.jpg" style="width: 100%; height: 100%; overflow: hidden; visibility: visible; left: 0px; top: 0px; z-index: 18; opacity: 1;"><div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="left top" data-kenburns="undefined" data-easeme="undefined" data-bgfit="cover" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined"><div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat" data-lazydone="undefined" src="images/slider/slide-img2.jpg" data-src="images/slider/slide-img2.jpg" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;images/slider/slide-img2.jpg&quot;); background-size: cover; background-position: left top; width: 100%; height: 100%; opacity: 0;"></div></div>
                <div class="info">
                  <div class="tp-caption ExtraLargeTitle sft slide2 tp-resizeme start" data-x="45" data-y="165" data-endspeed="500" data-speed="500" data-start="1100" data-easing="Linear.easeNone" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" style="z-index: 2; white-space: nowrap; padding: 0px; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 68px; border-width: 0px; margin: 0px; letter-spacing: 0px; font-size: 16px; left: 190.608px; top: 163.02px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, -49.359, 0, 1);"><span style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 30px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 36px;">Big Sale</span></div>
                  <div class="tp-caption LargeTitle sfl tp-resizeme start" data-x="45" data-y="220" data-endspeed="500" data-speed="500" data-start="1300" data-easing="Linear.easeNone" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" style="z-index: 3; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 69px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 48px; left: 190.608px; top: 217.36px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, -49.359, 0, 0, 1);">New Fashion</div>
                  <div class="tp-caption Title sft tp-resizeme start" data-x="45" data-y="300" data-endspeed="500" data-speed="500" data-start="1500" data-easing="Power2.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 20px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 16px; left: 190.608px; top: 296.4px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, -49.359, 0, 1);">Look great &amp; feel amazing in our stunning dresses.</div>
                  <div class="tp-caption sfb tp-resizeme start" data-x="45" data-y="350" data-endspeed="500" data-speed="500" data-start="1500" data-easing="Linear.easeNone" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" style="z-index: 4; white-space: nowrap; transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 17px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; font-size: 12px; left: 190.608px; top: 345.8px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, 49.359, 0, 1);"><a href="#" class="buy-btn" style="transition: all 0.4s ease 0s; min-height: 0px; min-width: 0px; line-height: 20px; border-width: 1px; margin: 0px 0px 0px 9.88px; padding: 12px 20px; letter-spacing: 1px; font-size: 14px;">Buy Now</a></div>
                </div>
              </li>
            </ul>
          <div class="tp-loader spinner0" style="visibility: hidden; opacity: 0;"><div class="dot1"></div><div class="dot2"></div><div class="bounce1"></div><div class="bounce2"></div><div class="bounce3"></div></div><div class="tp-bannertimer" style="visibility: visible; width: 0%;"></div></div>
        <div class="tp-bullets tp-thumbs round" style="width: 406px; height: 56px; bottom: 20px; left: 50%; margin-left: -307.5px;"><div class="tp-mask" style="width: 400px; height: 50px;"><div class="tp-thumbcontainer" style="left: -200px;"><div class="bullet thumb first" style="background-color: rgba(0, 0, 0, 0); position: relative; width: 200px; height: 50px; background-size: cover; background-position: center center; background-image: url(&quot;images/slider/slide-img1.jpg&quot;) !important;"></div><div class="bullet thumb selected" style="background-color: rgba(0, 0, 0, 0); position: relative; width: 200px; height: 50px; background-size: cover; background-position: center center; background-image: url(&quot;images/slider/slide-img3.jpg&quot;) !important;"></div><div class="bullet thumb last" style="background-color: rgba(0, 0, 0, 0); position: relative; width: 200px; height: 50px; background-size: cover; background-position: center center; background-image: url(&quot;images/slider/slide-img2.jpg&quot;) !important;"></div></div></div></div><div style="position: absolute; top: 250px; margin-top: -28px; left: -84.5px;" class="tp-leftarrow tparrows default"></div><div style="position: absolute; top: 250px; margin-top: -28px; right: 124.5px;" class="tp-rightarrow tparrows default"></div></div><div class="tp-fullwidth-forcer" style="width: 100%; height: 500px;"></div></div>
      </div>